language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
deploy:
    # test pypi
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "Dan.Riti"
    password:
      secure: "H8LajeriIeKVtFVLZ89UfPEUEAYiI0k/sXVG2VT6zGx2V4KTOLZwWQTAgTUhX+Wx6zacOZh6jRbT9IX5kYYzCpr/Z/K2OZgoycR+dVAulmQrmlqBUQr63Wxd7Perjn24rkdcqRuWYqOTnNWourtiCCOOfEJFK4tYGD//w9TcrZk="
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

    # production pypi
  - provider: pypi
    distributions: sdist
    user: "Dan.Riti"
    password:
      secure: "O1ZAG/HomgyOoD4gxKmoA2HnZWx3uzBqOaBrcocu5aR/PRzhPTz6u6if0TO1TryJPt5VrfrVB3YwH8NOUls3g6WszmkagAQCrMftivme8esm/DvZzDwMEP4qt/d/1m4F4EvbDd+ZyUdjTAlIM4DE25dy9cyfL8EctQRqvGZE9Ck="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
