language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
deploy:
    # test pypi
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "Dan.Riti"
    password:
      secure: "H8LajeriIeKVtFVLZ89UfPEUEAYiI0k/sXVG2VT6zGx2V4KTOLZwWQTAgTUhX+Wx6zacOZh6jRbT9IX5kYYzCpr/Z/K2OZgoycR+dVAulmQrmlqBUQr63Wxd7Perjn24rkdcqRuWYqOTnNWourtiCCOOfEJFK4tYGD//w9TcrZk="
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

    # production pypi
  - provider: pypi
    distributions: sdist
    user: "Dan.Riti"
    password:
      secure: "V3vD9nUk3FNhilxvzV2W/XTlerHMwYImPTlqFA20+dihJuUYsl20K0oYQ8gUH8xxre4vR5lQciK9h4RV8TToZzpLS6HAd2e4pp5u0dzri15jdfkWDSQv3YnoMqJt9L4SuqY15AwupI4jnsC/6u3GMXCoRdWyWBLaP/Vr0tNPXnw="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
