language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
deploy:
    # test pypi
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "Dan.Riti"
    password:
      secure: "H8LajeriIeKVtFVLZ89UfPEUEAYiI0k/sXVG2VT6zGx2V4KTOLZwWQTAgTUhX+Wx6zacOZh6jRbT9IX5kYYzCpr/Z/K2OZgoycR+dVAulmQrmlqBUQr63Wxd7Perjn24rkdcqRuWYqOTnNWourtiCCOOfEJFK4tYGD//w9TcrZk="
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

    # production pypi
  - provider: pypi
    distributions: sdist
    user: "Dan.Riti"
    password:
      secure: "IEsQdc5lq6swLIqchjW67f/gVDm02Vc6MJgQUSe9oQm0hcuc0LG+HqDkiZ4bMBFv9C6Z+2M/ULQUTGr9Up7BDEhYtHLjt4j9pLMNZo/R7OUOioOtuiBobUXT9f+13ag2BfGPfYDs8FG/F6l1Pl6rmIjHOWJsRSULRACxuuBwFtI="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
